name: comic_viwer_practice
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # architecture
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0
  freezed_annotation: ^2.0.3
  flame: ^1.4.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true